language: baseh

before_script:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-backports restricted main universe"
  - sudo apt-get update -qq
  - sudo apt-get install -qq shellcheck

script:
  - shellcheck --shell=bash ffscreencast

